"""A pty-based harness for testing interactive zsh behaviour.

zle widgets (line editor code) only run against a real terminal, so testing the
prompt means driving an actual interactive shell through a pseudo-terminal and
reading back what it painted. Nothing here needs third-party packages.
"""
import os
import pty
import re
import select
import shutil
import signal
import tempfile
import time
import traceback

# CSI sequences, OSC strings (BEL- or ST-terminated), charset selects, carriage returns.
_ANSI = re.compile(
    r"\x1b\[[0-9;?]*[a-zA-Z]"
    r"|\x1b\][^\x07\x1b]*(?:\x07|\x1b\\)"
    r"|\x1b[()][AB0]"
    r"|\r"
)


def strip_ansi(text):
    """Remove terminal control sequences, leaving the visible characters."""
    return _ANSI.sub("", text)


def find_liquidprompt():
    """Locate liquidprompt, or return None.

    Checked in priority order: the location install.sh clones into, then a manual
    clone. Hardcoding only the latter would make every prompt test silently SKIP
    once the installer has run — a failure that looks exactly like success.
    """
    for candidate in (
        os.path.expanduser("~/.local/share/liquidprompt/liquidprompt"),
        os.path.expanduser("~/liquidprompt/liquidprompt"),
    ):
        if os.path.exists(candidate):
            return candidate
    return None


def make_zdotdir(repo, modules, extra=""):
    """Build a throwaway ZDOTDIR whose .zshrc sources exactly `modules`.

    Isolating the shell from the developer's real config is what makes these
    tests meaningful in CI and reproducible locally.
    """
    d = tempfile.mkdtemp(prefix="dotfiles-test-")
    lines = [
        "# Generated by tests/lib/harness.py",
        "setopt PROMPT_SUBST",
        f"DOTFILES_DIR={repo!r}",
    ]
    for m in modules:
        lines.append(f"source {os.path.join(repo, 'zsh', m)!r}")
    lines.append(extra)
    with open(os.path.join(d, ".zshrc"), "w") as fh:
        fh.write("\n".join(lines) + "\n")
    return d


class Shell:
    """An interactive zsh running in a pty."""

    def __init__(self, zdotdir, env=None):
        self.zdotdir = zdotdir
        self._env = env or {}
        self.pid, self.fd = pty.fork()
        if self.pid == 0:                      # child
            os.environ["ZDOTDIR"] = zdotdir
            os.environ["HOME"] = zdotdir
            os.environ["TERM"] = "xterm-256color"
            os.environ["COLUMNS"] = "120"
            os.environ["LINES"] = "40"
            os.environ.update(self._env)
            os.execvp("zsh", ["zsh", "-i"])
        self._buf = ""

    def send(self, text):
        os.write(self.fd, text.encode())

    def read(self, seconds=1.0):
        """Drain output for `seconds`, returning everything read in that window."""
        out = b""
        deadline = time.time() + seconds
        while time.time() < deadline:
            ready, _, _ = select.select([self.fd], [], [], 0.1)
            if ready:
                try:
                    chunk = os.read(self.fd, 65536)
                except OSError:
                    break
                if not chunk:
                    break
                out += chunk
        return out.decode("utf-8", "replace")

    def close(self):
        try:
            os.write(self.fd, b"exit\n")
        except OSError:
            pass
        try:
            # Closing the master hangs up the slave's controlling terminal,
            # which SIGHUPs the shell if "exit" alone didn't finish it off.
            os.close(self.fd)
        except OSError:
            pass
        self._reap(timeout=2.0)
        shutil.rmtree(self.zdotdir, ignore_errors=True)

    def _reap(self, timeout):
        """Wait for the child to exit, escalating to SIGKILL, then reap it.

        A single non-blocking waitpid() right after signalling exit races the
        child's own shutdown: if the shell hasn't finished processing "exit" or
        handling SIGHUP yet, that one-shot check finds it still running, and
        since nothing ever waits on it again, it becomes a permanent zombie for
        the life of this process. Poll until it's actually gone.
        """
        deadline = time.time() + timeout
        while time.time() < deadline:
            try:
                pid, _ = os.waitpid(self.pid, os.WNOHANG)
            except ChildProcessError:
                return  # already reaped
            if pid == self.pid:
                return
            time.sleep(0.02)
        try:
            os.kill(self.pid, signal.SIGKILL)
        except OSError:
            pass
        try:
            os.waitpid(self.pid, 0)
        except ChildProcessError:
            pass

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        self.close()
        return False


def run_tests(namespace):
    """Run every test_* callable in `namespace`. Returns the failure count."""
    failures = 0
    for name in sorted(k for k in namespace if k.startswith("test_")):
        fn = namespace[name]
        if not callable(fn):
            continue
        try:
            fn()
            print(f"  PASS {name}")
        except Exception:
            failures += 1
            print(f"  FAIL {name}")
            print("    " + traceback.format_exc().replace("\n", "\n    "))
    return failures
